# Generated by Django 4.2.5 on 2023-11-08 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_users', '0006_customuser_first_name_customuser_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('Customer', 'Customer'), ('Counter', 'Counter'), ('Manager', 'Manager')], default='Customer', max_length=20),
        ),
    ]
