# Generated by Django 4.2.5 on 2023-10-04 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour_package', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourpackage',
            name='is_paid',
        ),
    ]
