# Generated by Django 4.2.5 on 2023-10-05 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_package', '0002_remove_tourpackage_is_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourpackage',
            name='image_1',
            field=models.ImageField(upload_to='tour_packages'),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='tour_packages'),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='tour_packages'),
        ),
    ]
