# Generated by Django 4.2.5 on 2023-11-08 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_is_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='is_paid',
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Un Paid', 'Unpaid'), ('Canceled', 'Canceled'), ('Ongoing', 'Ongoing'), ('Done', 'Done')], default='Un Paid', max_length=20),
        ),
    ]
